### ISSUE TITLE
Documentation fails to build with sphinx-4.0.2

### ISSUE THREAD

**Issue by Aniket-Pradhan** [snakemake/snakemake#1071]
**Snakemake version**: 6.5.1

**Describe the bug**
Documentation fails to build with sphinx-4.0.2 as `app.add_stylesheet` was depreceated. Please refer to [this](https://github.com/sphinx-doc/sphinx/issues/7747) issue for more information.

**Logs**
```bash
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v4.0.2
Exception occurred:
  File "/builddir/build/BUILD/snakemake-6.5.1/docs/conf.py", line 281, in setup
    app.add_stylesheet('sphinx-argparse.css')
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
```

Complete logs are [here](https://kojipkgs.fedoraproject.org//work/tasks/3785/71183785/build.log)

**Comment by corneliusroemer** [comment]
@Aniket-Pradhan thanks for the report. Could you test if this PR fixes it?
https://github.com/corneliusroemer/snakemake/tree/patch-2

I replaced with `add_css_file` as described by you.

**Comment by Aniket-Pradhan** [comment]
Yep, it works fine for the new version of sphinx. Thanks for the PR 😄

**Comment by corneliusroemer** [comment]
Great :)
How come you tried building the docs? Do you use Snakemake?

**Comment by Aniket-Pradhan** [comment]
We are using sphinx to build the docs (through the makefile).

```bash
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
```

We have added the same patch when building the docs for the Fedora repositories. You could view it [here](https://src.fedoraproject.org/rpms/snakemake/blob/rawhide/f/snakemake.spec#_91). The build logs for the same are available [here](https://kojipkgs.fedoraproject.org//work/tasks/3173/71303173/build.log). One can also confirm from the build logs that it builds perfectly.

**Comment by Aniket-Pradhan** [comment]
Also, as of sphinx v1.3, [`sphinxcontrib-napoleon`](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/) is bundled with `sphinx` and hence I think we should also correct the import path in [`conf.py`](https://github.com/snakemake/snakemake/blob/main/docs/conf.py#L40) from:

```
sphinxcontrib.napoleon
```

to
```
sphinx.ext.napoleon
```

We could probably raise a new ticket/PR for that or add in to the existing PR. What do you say @corneliusroemer ?

We have also patched this in our spec file using sed [here](https://src.fedoraproject.org/rpms/snakemake/blob/rawhide/f/snakemake.spec#_87).

**Comment by johanneskoester** [comment]
> Also, as of sphinx v1.3, [`sphinxcontrib-napoleon`](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/) is bundled with `sphinx` and hence I think we should also correct the import path in [`conf.py`](https://github.com/snakemake/snakemake/blob/main/docs/conf.py#L40) from:
> 
> ```
> sphinxcontrib.napoleon
> ```
> 
> to
> 
> ```
> sphinx.ext.napoleon
> ```
> 
> We could probably raise a new ticket/PR for that or add in to the existing PR. What do you say @corneliusroemer ?
> 
> We have also patched this in our spec file using sed [here](https://src.fedoraproject.org/rpms/snakemake/blob/rawhide/f/snakemake.spec#_87).

Sorry, haven't seen your comment before. A new PR would be very welcome, thanks!

**Comment by Aniket-Pradhan** [comment]
@johanneskoester , sure will create a new PR for the same. :D
