### ISSUE TITLE
:bug: Snakemake-minimal error reading config file

### ISSUE THREAD

**Issue by enryH** [snakemake/snakemake#2276]
**Snakemake version**
`snakemake-minimal=7.26.0` installed using conda from `bioconda`.

```
snakemake-minimal         7.26.0             pyhdfd78af_0    bioconda
```

**Describe the bug**

Using github runners `macos-latest`, `windows-latest` and `ubuntu-lastest` the config file of a workflow 
is not read. The introduction of the yte package for reading config files seems to cause the error.

**Logs**
```bash
AttributeError in file /home/runner/work/repo/workflow/Snakefile, line 6:
module 'plac' has no attribute 'flg'
  File "/home/runner/work/work/repo/workflow/Snakefile", line 6, in <module>
  File "/usr/share/miniconda3/envs/pkg/lib/python3.8/site-packages/yte/__init__.py", line 74, in <module>
Error: Process completed with exit code 1.
```

**Minimal example**

**Additional context**

**Comment by maarten-k** [comment]
Can you check the "plac"  and  "yte" versions in your environment? I think this bug is introduced in #2269

**Comment by enryH** [comment]
Yes sure
```
plac                      0.9.6                      py_1    conda-forge
yte                       1.5.1              pyha770c72_2    conda-forge
```

for the `ubuntu-latest` image.

**Comment by maarten-k** [comment]
It looks like that fastai, needs spacy, which needs an old version of plac. 

Snakemake needs YTE which needs a modern version of plac, but YTE  does not restrict the use of a minimal version number of plac This should be considered as a bug.

However, your environment file is quite big and at a certain point all dependencies become a hairball that is unmanageable. The version of programs are not fixed and unwanted behaviour might occur.( features in third-party software might disappear or change) . I advise using the integrated package manager of snakemake to trim down the size of the environment file https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#integrated-package-management.

**Comment by enryH** [comment]
That is a fair point... I'll add rule specific dependency files to resolve this issue.

**Comment by enryH** [comment]
For me setting a minimal plac version solves the issue ( `1.0`).

**Comment by maarten-k** [comment]
This is resolved since https://github.com/conda-forge/yte-feedstock/pull/23 is merged. Please close this ticket.
