### ISSUE TITLE
Can no longer explicitely import snakemake from snakemake.script

### ISSUE THREAD

**Issue by vandalt** [snakemake/snakemake#4113]
**Snakemake version**

`snakemake 9.17.1`

**Describe the bug**

For `snakemake<9.17.0`, I was able to add 

```python
from snakemake.script import snakemake
```

at the top of my script so my editor would recognize the snakemake object. This is still documented here: https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#python.

After updating to `snakemake>=9.17`, I get this error in the output:

```python
Traceback (most recent call last):
  File "/home/vandal/scratch/snakemake-zenodo/.snakemake/scripts/tmpsokddoba.generate.py", line 6, in <module>
    from snakemake.script import snakemake
ImportError: cannot import name 'snakemake' from 'snakemake.script' (/home/vandal/miniforge3/envs/snakemake-zenodo/lib/python3.14/site-packages/snakemake/script/__init__.py)
RuleException:
CalledProcessError in file "/home/vandal/scratch/snakemake-zenodo/Snakefile", line 5:
Command 'set -euo pipefail;  /home/vandal/miniforge3/envs/snakemake-zenodo/bin/python /home/vandal/scratch/snakemake-zenodo/.snakemake/scripts/tmpsokddoba.generate.py' returned non-zero exit status 1.
```

This seems to have been introduced in commit ffb19e7 (@fgvieira @johanneskoester).

Let me know if there is anything I can do to help debug or fix this.

Thank you!

**Comment by vandalt** [comment]
A workaround, albeit not as clean, is this:

```python
try:
    snakemake
except Exception:
    snakemake = Snakemake()
```

**Comment by fgvieira** [comment]
Try:
`from snakemake.io.container import Snakemake`

**Comment by vandalt** [comment]
Yes sorry I wasn't clear above, that's what I am currently doing:

```python
from snakemake.io.container import Snakemake

try:
    snakemake
except Exception:
    snakemake = Snakemake()
```

But that still feels less clean than the previous `from snakemake.script import snakemake`.

I'm adding the try/except because without it I guess the empty `Snakemake` object would either fail or replace the one created by the script pre-amble?

**Comment by fgvieira** [comment]
It might be this line that should be moved to `snakemke.io.container`:
https://github.com/snakemake/snakemake/blob/4bba4a938b426680cbc63bcada10a444d960ab9c/src/snakemake/script/__init__.py#L50

But are you trying to do? Can you use `Snakemake` instead of `snakemake`?

**Comment by vandalt** [comment]
I am just trying to import snakemake at the top of a script so that linting and completion work in an editor or IDE. The previous behaviour was that this line changed nothing at runtime, but it enabled the editor to "know" about the `snakemake` object's attribute without running anything. This means that typing `snakemake.out|`, you could have completion for `snakemake.output`, or see its attributes, etc.

Relevant line from [the docs](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#python):

> It is also possible to explicitly import the snakemake object in the script like from snakemake.script import snakemake to enable code completion, linting and type checking your python code in IDEs.

**Comment by fgvieira** [comment]
Maybe moving line:
https://github.com/snakemake/snakemake/blob/4bba4a938b426680cbc63bcada10a444d960ab9c/src/snakemake/script/__init__.py#L50

to `snakemake.io.container` and importing as:
```
from snakemake.io.container import snakemake
```
Can you give it a try?

**Comment by johanneskoester** [comment]
We should however fix the breaking change, this was not intended.

**Comment by johanneskoester** [comment]
Working on a fix now.

**Comment by johanneskoester** [comment]
What works is this here: https://github.com/snakemake/snakemake/pull/4116
What I can't get to work is the import without the TYPE_CHECKING-if around it. I think with TYPE_CHECKING around it is also cleaner, but it would be a breaking change (sorry for that). The problem is that we can't really do what we did before, because it implies that one would have to import snakemake.script in the preamble. This we wanted to avoid by introducing the container module, because that enables us to maintain compatibility with old python versions in scripts without having to maintain the same compatibility in snakemake and its dependencies.

**Comment by johanneskoester** [comment]
Ok, closing this with the fix being merged and released. Note that we made a final change on the location of the type hint. It is now

```python
from typing import TYPE_CHECKING

    if TYPE_CHECKING:
        from snakemake.iocontainers import snakemake
```
