### ISSUE TITLE
Workflow error: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by vsoch** [snakemake/snakemake#426]
**Snakemake version**
inventory branch, 

**Describe the bug**
I'm running a previously working pipeline, and it's reporting that a `'str' object has no attribute 'decode'`
```
      AttributeError in line 13 of /workdir/workflow/rules/calling.smk:
      'str' object has no attribute 'decode'
        File "/opt/conda/envs/snakemake/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2135, in run_wrapper
        File "/workdir/workflow/rules/calling.smk", line 13, in __rule_render_scenario
        File "/opt/conda/envs/snakemake/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 529, in _callback
        File "/opt/conda/envs/snakemake/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        File "/opt/conda/envs/snakemake/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
        File "/opt/conda/envs/snakemake/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2201, in run_wrapper
      Shutting down, this might take some time.
      Exiting because a job execution failed. Look above for error message
      Complete log: /workdir/.snakemake/log/2020-06-02T172653.865589.snakemake.log
```
Line 13 being referenced is the "script" one here

![image](https://user-images.githubusercontent.com/814322/83552624-49185500-a4c7-11ea-9c06-01e22b0612ed.png)

@johanneskoester have you seen this before?

**Comment by wir963** [comment]
I am getting the same error when I run a previously working workflow using snakemake 5.19.0. When I downgrade to snakemake 5.13.0, the workflow works again.

**Comment by vsoch** [comment]
This might have been a bug - did you try the latest version (I think 5.19.3?)

**Comment by wir963** [comment]
When I update to 5.19.3, the error goes away. Thanks!

**Comment by vsoch** [comment]
Great! I think we’ve resolved this so I’m going to close the issue.
