### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ignore_incomplete' during conda_create_envs

### ISSUE THREAD

**Issue by komorn** [snakemake/snakemake#2637]
Hello,

I am encountering an error when I try to run this command:
`snakemake --use-conda --conda-frontend mamba --conda-create-envs-only --cores 10`.

The error says:
```
Traceback (most recent call last):
  File "/home2/komornikova/mambaforge/envs/transxpress/lib/python3.12/site-packages/snakemake/cli.py", line 1941, in args_to_api
    dag_api.conda_create_envs()
  File "/home2/komornikova/mambaforge/envs/transxpress/lib/python3.12/site-packages/snakemake/api.py", line 651, in conda_create_envs
    self.workflow_api._workflow.conda_create_envs()
  File "/home2/komornikova/mambaforge/envs/transxpress/lib/python3.12/site-packages/snakemake/workflow.py", line 987, in conda_create_envs
    ignore_incomplete=self.execution_settings.ignore_incomplete,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ignore_incomplete'
```

**Snakemake version**
I am using snakemake 8.2.1

I want to create environments for my Snakefile prior to running the whole pipeline and this command always worked for me until today. I do not see any changes that could have affected creating environments. Could you help me with resolving this error?

**Comment by mfouesneau** [comment]
same issue with 8.3.1

**Comment by cultice-7** [comment]
> same issue with 8.3.1 (Python 3.11.5) The workflow works, but not the --dag (--dag worked with version 7.32.3)

I'm having a similar issue

**Comment by cademirch** [comment]
Also having this issue with creating envs. Seems like the issue is the `ignore_incomplete` attribute is not set in the `execution_settings`. I'm not familiar with the new API, but in `conda_list_envs`, `ignore_incomplete` is just set to `False`:

https://github.com/snakemake/snakemake/blob/2ecb21ba04088b9e6850447760f713784cf8b775/snakemake/workflow.py#L966-L971

Doing this in `conda_create_envs` results in expected behavior in the simplest test case:

```
# Snakefile
rule test:
    output: "hi.txt"
    conda: "env.yaml" 
    shell: "echo hi > {output}"

# env.yaml
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - samtools
```

Not sure if this is the proper fix, but it seems like it could be. Looks like it would be the same for `printdag`. I can't really think of how considering or not considering incomplete output files (which I assume `ignore_incomplete` controls) would effect which conda envs need to be built. For printing the dag, I think it could make sense in the case where you would not need to print rules for incomplete files.

Anyway, opened a PR for this, lets see what @johanneskoester thinks.

**Comment by cademirch** [comment]
#2653 in 8.4.0 fixes this.

**Comment by MarwanMabrouk** [comment]
@johanneskoester this issue can be closed
