### ISSUE TITLE
conda/snakemake not detecting networkx or pygraphiz for reports

### ISSUE THREAD

**Issue by pdimens** [snakemake/snakemake#1014]
**Snakemake version**
Note the Snakemake version for which you experience the bug.
```
> snakemake --version
6.4.0
```

**Describe the bug**
Trying to use the report function but getting an error that packages are not installed, yet they already are.

**Logs**
```
WorkflowError:
Python packages networkx and pygraphviz must be installed to create reports.
ImportError: cannot import name 'gcd' from 'fractions' (/home/pdimens/.conda/envs/lepwrap/lib/python3.9/fractions.py)
  File "/home/pdimens/.conda/envs/lepwrap/lib/python3.9/site-packages/snakemake/report/__init__.py", line 802, in auto_report
  File "/home/pdimens/.conda/envs/lepwrap/lib/python3.9/site-packages/snakemake/report/__init__.py", line 557, in rulegraph_d3_spec
```

**Minimal example**
```bash
snakemake --snakefile ./rules/LepAnchor.smk --directory . --report ./LA.html
```

**Additional context**
It seems both `networkx` and `pygraphviz` are installed:
```
> conda install -c conda-forge networkx pygraphviz
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.0
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.
```

**Comment by mbargull** [comment]
> `ImportError: cannot import name 'gcd' from 'fractions' (/home/pdimens/.conda/envs/lepwrap/lib/python3.9/fractions.py)`

This is most likely coming from `networkx<2.4` running on `python=3.9`. `fractions.gcd` has been deprecated since Python 3.5 and is only available as `math.gcd` from 3.9 on, but only `networkx>=2.4` imports `math.gcd`.

You should be able to either `conda install networkx\>=2.4` or `conda install python\<3.9` to fix this.

(If this causes you further problems, you could ask at https://github.com/conda-forge/networkx-feedstock/issues whether the dependency information for `networkx<2.4` could be adjusted to carry `python<3.9`. OTOH, `networkx<2.4` is also more than 2 years old, so trying to install `>=2.4` would probably make sense anyway.)

**Comment by pdimens** [comment]
Thanks for the response. Is there a reason the conda snakemake recipe doesn't include that dependency out of the box?

**Comment by mbargull** [comment]
Yes, `snakemake` works with `networkx<2.4` and as such it wouldn't need to depend on `networkx>=2.4`.
The problem here is that `snakemake`'s dependencies are fine, but the upstream's dependencies are too loose which then leads to the observed incompatibility. I.e., the correct fix would be to add a restriction to the upstream dependency as outlined in the previous comment.
One could include a `>=2.4` constraint (with an explanatory comment!) to `snakemake'`s `networkx` requirement as a workaround. But I'll leave that decision up to the current maintainers.

Can you confirm if 
> either `conda install networkx\>=2.4` or `conda install python\<3.9`

fixes the issue for you?

**Comment by pdimens** [comment]
I had to install it as 
`conda install -c conda-forge/labels/main networkx` and it worked.
