### ISSUE TITLE
Question of usage of explicit import of snakemake object from snakemake.scripts

### ISSUE THREAD

**Issue by dandaman** [snakemake/snakemake#2983]
Hi,
the doc states that one can "enable code completion, linting and type checking your python code in IDEs" by explicitely importing from snakemake.script.

https://github.com/snakemake/snakemake/blob/e8735c1477a2a82110757ba86bbd1ccbcaf327ba/docs/snakefiles/rules.rst#L1138

Does this only work in a 'run' block or when using the --debug option of snakemake?
I've tried the code as it is suggested in the doc, but get the following error:

```python
python
Python 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

from snakemake.script import snakemake

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'snakemake' from 'snakemake.script' (<my_conda_path>/pq/lib/python3.12/site-packages/snakemake/script/__init__.py). Did you mean: 'Snakemake'?
```

Should this still work in snakemake 8.16.0 ?

**Comment by jlumpe** [comment]
I think this is only supposed to work in a script:

```
# Snakefile:

rule my_rule:
    script: 'scripts/my_rule.py'
```

```python
# scripts/my_rule.py:

from snakemake.script import snakemake
```
