### ISSUE TITLE
--batch cli argument error

### ISSUE THREAD

**Issue by alxsimon** [snakemake/snakemake#2643]
**Snakemake version** 8.2.3
Freshly installed in its own conda environment with python 3.11

**Describe the bug**
Error when using the --batch cli argument (was working in v7)

**Logs**
```
> snakemake --software-deployment-method conda apptainer -c 50 --batch preprocessing=1/10 -n

Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2038, in main
    parser, args = parse_args(argv)
                   ^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 1629, in parse_args
    args = parser.parse_args(argv)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/snakemake/lib/python3.12/site-packages/configargparse.py", line 797, in parse_args
    args, argv = self.parse_known_args(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/snakemake/lib/python3.12/site-packages/configargparse.py", line 979, in parse_known_args
    namespace, unknown_args = argparse.ArgumentParser.parse_known_args(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/snakemake/lib/python3.12/argparse.py", line 1924, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/snakemake/lib/python3.12/argparse.py", line 2136, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/snakemake/lib/python3.12/argparse.py", line 2076, in consume_optional
    take_action(action, args, option_string)
  File "/opt/miniconda3/envs/snakemake/lib/python3.12/argparse.py", line 1984, in take_action
    argument_values = self._get_values(action, argument_strings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/snakemake/lib/python3.12/argparse.py", line 2522, in _get_values
    value = self._get_value(action, arg_string)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/snakemake/lib/python3.12/argparse.py", line 2555, in _get_value
    result = type_func(arg_string)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 149, in parse_batch
    if args.batch is not None:
       ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'batch'
```

**Comment by alxsimon** [comment]
Also tried the newest 8.3.1 without success.

**Comment by alxsimon** [comment]
As a minimal working example, I found I can replicate the issue with the `tests/test_batch` pipeline (https://github.com/snakemake/snakemake/blob/main/tests/test_batch/Snakefile).
Working with v7.32.4 and failing with v8.2.3 with command:
`snakemake -c 1 --batch aggregate=1/2`
