### ISSUE TITLE
Error collecting tests in tests/test_script_py/scripts/test_explicit_import.py

### ISSUE THREAD

**Issue by musicinmybrain** [snakemake/snakemake#2961]
**Snakemake version**

Current `main`, 5a4f72fe2bd79e33624328d2bcca50bb30da8e55.

**Describe the bug**

`ERROR collecting tests/test_script_py/scripts/test_explicit_import.py` in a virtualenv or in a Fedora RPM package build environment.

**Logs**

```
==================================================================================================== ERRORS ====================================================================================================
________________________________________________________________________ ERROR collecting tests/test_conda_python_script/test_script.py ________________________________________________________________________
import file mismatch:
imported module 'test_script' has this __file__ attribute:
  /home/ben/src/forks/snakemake/tests/test_conda_python_3_7_script/test_script.py
which is not the same as the test file we want to collect:
  /home/ben/src/forks/snakemake/tests/test_conda_python_script/test_script.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
____________________________________________________________________ ERROR collecting tests/test_script_py/scripts/test_explicit_import.py _____________________________________________________________________
ImportError while importing test module '/home/ben/src/forks/snakemake/tests/test_script_py/scripts/test_explicit_import.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_script_py/scripts/test_explicit_import.py:1: in <module>
    from snakemake.script import snakemake
E   ImportError: cannot import name 'snakemake' from 'snakemake.script' (/home/ben/src/forks/snakemake/snakemake/script/__init__.py)
=========================================================================================== short test summary info ============================================================================================
ERROR tests/test_conda_python_script/test_script.py
ERROR tests/test_script_py/scripts/test_explicit_import.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================================== 2 errors in 1.27s ===============================================================================================
```

The `ERROR collecting tests/test_conda_python_script/test_script.py` is a longstanding issue, and I have been running `pytest` with `--ignore=tests/test_conda_python_script/test_script.py`. Maybe it should be reported separately, but I guess it’s working with the way you run tests upstream.

**Minimal example**

```
$ gh repo clone snakemake/snakemake
$ cd snakemake
$ python3.12 -m venv _e
$ . _e/bin/activate
(_e) $ pip install -e .
(_e) $ pip install pytest Pillow numpy pandas snakemake-executor-plugin-cluster-generic
(_e) $ python -m pytest
```
```

**Additional context**
<!--Add any other context about the problem here.-->

It looks like this was introduced in c85fb4b34ce983cb916bcce361d958d466ee1d07 / #2917.

I can also reproduce this when `snakemake` is installed system-wide in Fedora 40:

```
$ python3 -c 'from snakemake.scripts import snakemake'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'snakemake' from 'snakemake.script' (/home/ben/src/forks/snakemake/snakemake/script/__init__.py). Did you mean: 'Snakemake'?
```

On the other hand, `python3 -c 'from snakemake.script import Snakemake'` works.

**Comment by vandalt** [comment]
Hi!

I'm fairly new to Snakemake but was interested in understanding what #2917 was doing and stumbled on this issue. I'll try to add a bit of info (to the best of my understanding).

Indeed the error your showing (`ImportError: cannot import name 'snakemake' from 'snakemake.script'`) seems linked to #2917. However, I don't think, it's a bug, but rather the expected behaviour when running `from snakemake.script import snakemake` outside of a Snakemake "context", since `snakemake.script.snakemake` (lower case) is simply a type hint that can be used by editor. At execution time, the `snakemake` object needs to be created by snakemake, which is done by the boilerplate/preamble ([here](https://github.com/snakemake/snakemake/blob/e8735c1477a2a82110757ba86bbd1ccbcaf327ba/snakemake/script/__init__.py?plain=1#L564-L575) for example).

I think the main problem here is that the tests are not expected to be run with `pytest` on its own and a path should be passed as argument. This is what is done in the [.github/workflows/main.yaml](https://github.com/snakemake/snakemake/blob/e8735c1477a2a82110757ba86bbd1ccbcaf327ba/.github/workflows/main.yml?plain=1#L40) file. When running `pytest` on its own, the `test_script_py` directory gets interpreted as a test location, which gives me the same error as you get. When I run it indirecly via `pytest tests/tests.py -k test_script_python`, everything works on my end. However, the [testing guidelines](https://snakemake.readthedocs.io/en/stable/project_info/contributing.html#testing-guidelines) do indicate to run `pytest` on its own, which can lead to confusion (it did for me at least 😅).

I'm not sure if this is a code issue or a documentation issue, but I think it's the latter. If that's the case, I would have two suggestions:

- Update the testing guidelines example to have something like `pytest tests/tests.py` (or more files)
- Clarify in the [External scripts](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#python) documentation that explicit import provides linting/completion, but **not** a way to execute a script directly (with `python some_snakemake_script.py` or `python3 -c 'from snakemake.scripts import snakemake'`) and access an actual `snakemake` object.

Happy to contribute the docs update if people think it would be useful (if it's a code issue, I don't think I would be of much help, however).

Cc'ing @Hugovdberg as he implemented #2917.

Again, I'm new to snakemake so I might have misunderstood some parts here.

Thanks!

**Comment by Hugovdberg** [comment]
@vandalt You're right that the `snakemake.script.snakemake` object only contains data when the script is run in the workflow. It was not meant to allow running a script directly in python. Therefore, you're right in concluding that this is a documentation issue and that those points need clarification.

**Comment by musicinmybrain** [comment]
Thanks for the advice on this!

Expecting that `pytest` is always passed individual Python files is unusual – of hundreds of Python packages I maintain or have worked on in Fedora, Snakemake is nearly alone in this – but there is nothing really *wrong* with it.

I am working on adjusting Fedora’s [`snakemake` package](https://src.fedoraproject.org/rpms/snakemake) to run tests the same way as the [“Tests local” step in `.github/workflows/main.yml`](https://github.com/snakemake/snakemake/blob/e8735c1477a2a82110757ba86bbd1ccbcaf327ba/.github/workflows/main.yml?plain=1#L91-L99), and I’m getting much better results that way: a lot more tests are collected and executed.

I’m still working through some understanding some test failures that I’m seeing for the first time, in the tests that weren’t executed before, but the error reported here is not among the issues I’m seeing, so I think that – from my perspective – it’s safe to close this issue unless you want to use it to track some kind of documentation improvement.
