### PR TITLE
fix: add_stylesheet() was deprecated in Sphing v1.8 (#1071)

### LINKED ISSUE #1071: Documentation fails to build with sphinx-4.0.2
**Snakemake version**: 6.5.1

**Describe the bug**
Documentation fails to build with sphinx-4.0.2 as `app.add_stylesheet` was depreceated. Please refer to [this](https://github.com/sphinx-doc/sphinx/issues/7747) issue for more information.

**Logs**
```bash
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v4.0.2
Exception occurred:
  File "/builddir/build/BUILD/snakemake-6.5.1/docs/conf.py", line 281, in setup
    app.add_stylesheet('sphinx-argparse.css')
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
```

Complete logs are [here](https://kojipkgs.fedoraproject.org//work/tasks/3785/71183785/build.log)

### PR DESCRIPTION
**Pull request by corneliusroemer**
Should fix #1071 

I haven't tested this myself, but I'm fairly confident that the simple switch should not break anything.

The documentation is clear on this: https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_css_file

### CODE REVIEW

**Review by johanneskoester — APPROVED** [review]
Thank you!
